name: CI

on:
  push:
    branches: [main, master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    strategy:
      matrix:
        node-version: [18, 20, 22]

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - run: git config --global url."https://${{ secrets.GITHUB_TOKEN }}@github.com/".insteadOf "https://github.com/"

      - run: pnpm install --frozen-lockfile

      - run: |
          pnpm "build: all"

      - run: |
          pnpm "build: copy-metafiles"

      - run: pnpm test
